Draft ready for review: Video Transcriber Implementation Guide CN version
awslabs/aws-video-transcriber pull request #35
Opened 2021-12-06 06:42 UTC by rrxie

*Issue #, if available:*

*Description of changes:*

Hello, All,

Please review the Video Transcriber Implementation Guide (Chinese version) and let us know your comments. Thx.

Deng Mingtong/Xie Ru

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-12-06 08:13 UTC, zxkane requested changes

2021-12-06 08:13 UTC, zxkane commented on docs/en/cost.md
> +| Amazon Lambda                       | 10万次调用 （平均300ms，128M内存）               |   $0  |
AWS Lambda

2021-12-06 08:13 UTC, zxkane commented on docs/en/cost.md
> +您需要承担运行此解决方案时使用亚马逊云科技各个服务的费用。截止2021年12月，此解决方案主要包括以下费用：
why using Chinese in en doc?

2021-12-07 03:16 UTC, zxkane requested changes
Pls collaborate with mingtong to add github action to validate the docs generation for PRs.

2021-12-07 03:16 UTC, zxkane commented on docs/mkdocs.zh.yml
> +  - 更多资源: additional resources.md
did you build those pages as html with spaces in file name?

2021-12-07 03:16 UTC, zxkane commented on docs/en/cost.md
> +| Amazon API Gateway                  | 5万个请求               |   $0.17  |
add `use case` as well, for example, edit subscribers for 100 videos(one per 60 mins)

2021-12-07 03:16 UTC, zxkane commented on docs/zh/deployment.md
> +1. 登录到Amazon Web Service管理控制台，选择[中国区（北京）链接][template-china1]或[中国区（宁夏）链接][template-china2]启动Amazon CloudFormation模板。
`中国区（宁夏)` -> `由西云数据运营的亚马逊云科技中国（宁夏）区域`

same as 北京

2021-12-07 03:16 UTC, zxkane commented on docs/zh/deployment.md
> +| **TranscribeLanguage**    | zh-CN    | 默认的字幕处理语言 |
what are other supported values?

2021-12-07 03:16 UTC, zxkane commented on docs/zh/deployment.md
> +1. 登录到Amazon Web Service管理控制台，选择[海外区链接][template-global]启动Amazon CloudFormation模板。
`海外区` -> `AWS全球`

2021-12-07 03:16 UTC, zxkane commented on docs/zh/deployment.md
> +![](./images/user-guide-video-download-1.png)
where are image files?

2021-12-07 03:16 UTC, zxkane commented on docs/zh/welcome.md
> +- 字幕生成：支持MP4，MOV和MKV的视频格式；支持四个小时以内的视频（基于Amazon Transcribe的限制）。
是否有官方链接？

2021-12-07 03:16 UTC, zxkane commented on docs/zh/welcome.md
> +- 字幕翻译：支持从源语言翻译成目标语言，并生成字幕（**仅支持全球区域**）。
`仅支持全球区域` —> `仅全球区域部署版本支持`

2021-12-10 09:51 UTC, rrxie commented
Hello, All,

Please review the Video Transcriber Implementation Guide (English version) and let us know your comments. Thx.

Deng Mingtong/Xie Ru

2021-12-16 06:53 UTC, techeditor reviewed
From Pu

2021-12-16 06:58 UTC, techeditor commented on docs/zh/source.md
> +访问我们的[GitHub存储库](https://github.com/awslabs/aws-video-transcriber/)，下载此解决方案的源文件。视频字幕解决方案的模板是使用[Amazon Cloudformation](https://aws.amazon.com/cn/cloudformation)生成的。有关更多信息，请参阅README.md文件。
Cloudformation中F大写。

2021-12-16 09:56 UTC, techeditor reviewed
Chinese version review done.

2021-12-16 09:56 UTC, techeditor commented on docs/zh/deployment.md
> +在部署解决方案之前，建议您先查看本指南中有关架构图和区域支持等信息。然后按照下面的说明配置解决方案并将其部署到您的帐户中。
- "等信息。"中的句号应为逗号，或者后面的“然后”后面加逗号。
- “帐户”应为“账户”。

2021-12-16 09:56 UTC, techeditor commented on docs/zh/deployment.md
> +1. 申请经过ICP备案的域名。因为中国区域的CloudFront地址不能直接访问，这个域名会作为CNAME指向该解决方案部署后创建的CloudFront地址，您可以通过这个域名来访问。
“申请经过ICP备案的域名。” 改为 “经过ICP备案的域名。”或“为域名申请ICP备案。”

2021-12-16 09:56 UTC, techeditor commented on docs/zh/deployment.md
> +1. 登陆CloudFront的管理页面，选择该方案的**分配**。
“登陆”应为“登录”，请统改。

2021-12-16 09:56 UTC, techeditor commented on docs/zh/deployment.md
> +| **APIKey**  | 无  | 输入部署完成后登录系统所需的认证信息|
……所需的认证信息  后面增加句号。

2021-12-16 09:56 UTC, techeditor commented on docs/zh/deployment.md
> +您可以在Amazon CloudFormation控制台的状态列中查看堆栈的状态。正常情况下，大约10分钟内可以看到状态为**CREATE_COMPLETE**。
“大约10分钟内”去掉“内”。

2021-12-16 09:56 UTC, techeditor commented on docs/zh/deployment.md
> +2. 选中视频，然后选择**打开**。
选择**打开** 中的动词，如果对象是按钮或链接，建议使用“单击”的表述方式。

2021-12-16 09:56 UTC, techeditor commented on docs/zh/deployment.md
> +您可将已经生成好的字幕烧入到视频中制作出硬字幕视频。
断句：
您可将已经生成好的字幕烧入到视频中，制作出硬字幕视频。

2021-12-16 09:56 UTC, techeditor commented on docs/zh/deployment.md
> +- 视频如果处于编辑状态，选择视频和对应语言进入视频编辑页面进行下载。
改为：如果视频……

2021-12-16 09:56 UTC, techeditor commented on docs/zh/deployment.md
> +- 视频如果处于完成状态，可直接在**Videos**页面的**Completed**页签中下载视频对应语言的字幕或视频。
改为：如果视频……

2021-12-16 09:56 UTC, techeditor commented on docs/zh/architecture.md
> +下图展示的是使用默认参数部署视频字幕解决方案在亚马逊云科技中构建的环境。
使用默认的参数部署视频字幕解决方案后，在亚马逊云科技中构建的环境如下图所示。

2021-12-16 09:56 UTC, techeditor commented on docs/zh/architecture.md
> +4. 客户端从AWS Lambda获得signURL之后上传需要处理的视频
请确认signURL的表达方式：sign URL、signed URL、签名的URL……

2021-12-16 09:56 UTC, techeditor commented on docs/zh/cost.md
> +- 使用Amazon Transcribe处理音频的数量。本方案使用Amazon Transcribe从音频中提取文字，生成字幕
建议中文场景中，句末加句号。余同。

2021-12-16 09:56 UTC, techeditor commented on docs/zh/cost.md
> +| AWS Lambda | 1000次调用 （平均300ms，128M内存） | ¥0 |
128M 应为 128MB

2021-12-16 09:56 UTC, techeditor commented on docs/zh/cost.md
> +## 示例2: 以美国东部（弗吉尼亚北部）区域（us-east-1)为例，处理时长1小时视频，编辑操作500次，翻译字幕1万个字符
（us-east-1) 前后括号不一致。

2021-12-16 09:56 UTC, techeditor commented on docs/zh/cost.md
> +| AWS Lambda | 1000次调用 （平均300ms，128M内存） | $0 |
128M 应为 128MB

2021-12-22 07:39 UTC, merged